services: docker

before_install:
  - docker -v
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop

install:
  - docker-compose -f docker/docker-compose.yml build test

script:
  - "docker-compose -f docker/docker-compose.yml run test "

