version: '3'

services: 
  test:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment: 
      - CI=true
    command: yarn test -u

  dev:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports: 
      - 3000:3000
    command: yarn start
    volumes: 
      - "../src:/srv/example/src" 
